name: textmining_cpu
channels:
  - defaults
dependencies:
  - python==3.8.16
  - numpy==1.22.3
  - pandas==1.5.3
  - pillow==9.4.0
  - matplotlib==3.7.1
  - jupyter==1.0.0
  - scikit-learn==1.2.2
  - tensorflow==2.10.0
  - keras==2.10.0
  - pymc3==3.11.4
  - conda-forge::python-graphviz==0.20.1  # https://github.com/conda/conda/issues/12242
  - conda-forge::hdbscan==0.8.29  # https://github.com/MaartenGr/BERTopic/issues/62
  - pytorch::cpuonly
  - pytorch::pytorch==2.0.1  # for transformer
  - pytorch::torchvision==0.15.2
  - pip=23.0.1
  - pip:
    - arviz==0.14.0
    - beautifulsoup4==4.12.2
    - bertopic==0.14.0
    - customized-konlpy==0.0.64
    - gensim==4.3.0
    - hgtk==0.2.0
    - imbalanced-learn==0.10.1
    - kiwipiepy==0.15.1
    - konlpy==0.6.0
    - kornounextractor==0.0.32
    - networkx==3.1
    - nltk==3.7
    - seaborn==0.12.2
    - selenium==3.141.0
    - sentencepiece==0.1.99
    - soynlp==0.0.493
    - tensorflow-addons==0.15.0
    - transformers[tf-cpu]==4.29.2
    - urllib3==1.26.15
    - wordcloud==1.9.2
    - xgboost==1.7.3

# Following package is deliberately excluded
# - m2w64-toolchain  (see https://discourse.pymc.io/t/theano-compilation-error/7306/6 )