name: textmining_gpu
channels:
  - conda-forge
dependencies:
  - gensim==4.3.1
  - hdbscan==0.8.29
  - imbalanced-learn==0.10.1
  - jpype1==1.2.1
  - jupyter=1.0.0
  - lightgbm==3.1.1
  - matplotlib==3.5.1
  - nltk==3.7
  - numpy==1.22.3
  - pandas==1.4.1
  - pillow==9.5.0
  - pip==23.1.2
  - pymc3==3.11.2
  - python==3.8.16
  - pytorch==1.12.1
  - requests==2.31.0
  - selenium==4.9.1
  - sentencepiece==0.1.96
  - spacy==3.2.2
  - tensorflow-gpu==2.3.0
  - transformers==4.17.0
  - urllib3==2.0.2
  - wordcloud==1.9.2
  - xgboost==1.5.0
  - pip:
      - bertopic==0.15.0
      - customized_konlpy==0.0.64
      - hgtk==0.2.0
      - kiwipiepy==0.15.1
      - konlpy==0.6.0
      - kornounextractor==0.0.32
      - soynlp==0.0.493
      - tensorflow-addons==0.20.0
